"""standalone_core

Revision ID: 0001
Revises: 
Create Date: 2026-07-10 05:39:04.261257
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('default_model', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('reply_style', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_retries >= 0', name=op.f('ck_ai_profiles_max_retries_non_negative')),
    sa.CheckConstraint('timeout_seconds > 0', name=op.f('ck_ai_profiles_timeout_seconds_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_profiles'))
    )
    op.create_table('ai_runtime_settings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('default_model', sa.String(length=255), nullable=False),
    sa.Column('api_key_ciphertext', sa.Text(), nullable=True),
    sa.Column('api_key_hint', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runtime_settings'))
    )
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('session_ref', sa.String(length=1024), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_mode', sa.String(length=16), nullable=False),
    sa.Column('ai_profile_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=128), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("auto_reply_mode IN ('off', 'suggest', 'auto')", name=op.f('ck_whatsapp_accounts_auto_reply_mode_valid')),
    sa.CheckConstraint("status IN ('new', 'qr_pending', 'connecting', 'online', 'offline', 'error', 'logged_out')", name=op.f('ck_whatsapp_accounts_status_valid')),
    sa.ForeignKeyConstraint(['ai_profile_id'], ['ai_profiles.id'], name=op.f('fk_whatsapp_accounts_ai_profile_id_ai_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_accounts'))
    )
    op.create_index('uq_whatsapp_accounts_one_primary', 'whatsapp_accounts', ['is_primary'], unique=True, sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary IS TRUE'))
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('remote_jid', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('lid', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_contacts_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('account_id', 'remote_jid', name='uq_contacts_account_remote_jid')
    )
    op.create_index('ix_contacts_account_display_name', 'contacts', ['account_id', 'display_name'], unique=False)
    op.create_index('ix_contacts_account_phone_number', 'contacts', ['account_id', 'phone_number'], unique=False)
    op.create_table('whatsapp_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('received', 'processed', 'failed')", name=op.f('ck_whatsapp_events_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_whatsapp_events_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_events')),
    sa.UniqueConstraint('event_id', name='uq_whatsapp_events_event_id')
    )
    op.create_index('ix_whatsapp_events_account_status_occurred', 'whatsapp_events', ['account_id', 'status', 'occurred_at'], unique=False)
    op.create_table('contact_ai_overrides',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('reply_style', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_contact_ai_overrides_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_ai_overrides_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'contact_id', name=op.f('pk_contact_ai_overrides'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('remote_jid', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_operator_id', sa.String(length=36), nullable=True),
    sa.Column('ai_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("ai_mode IN ('off', 'suggest', 'auto')", name=op.f('ck_conversations_ai_mode_valid')),
    sa.CheckConstraint("type IN ('dm', 'group')", name=op.f('ck_conversations_type_valid')),
    sa.CheckConstraint('unread_count >= 0', name=op.f('ck_conversations_unread_count_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_conversations_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversations_contact_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('account_id', 'remote_jid', name='uq_conversations_account_remote_jid')
    )
    op.create_index('ix_conversations_account_unread', 'conversations', ['account_id', 'unread_count'], unique=False)
    op.create_index(
        'ix_conversations_account_archived_last_message',
        'conversations',
        ['account_id', 'archived', sa.literal_column('last_message_at DESC')],
        unique=False,
    )
    op.create_index(
        'ix_conversations_account_pinned_last_message',
        'conversations',
        ['account_id', 'pinned', sa.literal_column('last_message_at DESC')],
        unique=False,
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('wa_message_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('sender_jid', sa.String(length=255), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_metadata', sa.JSON(), nullable=True),
    sa.Column('quoted_message_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name=op.f('ck_messages_direction_valid')),
    sa.CheckConstraint("message_type IN ('text', 'image', 'audio', 'video', 'document', 'system')", name=op.f('ck_messages_message_type_valid')),
    sa.CheckConstraint("status IN ('received', 'queued', 'sending', 'sent', 'delivered', 'read', 'failed')", name=op.f('ck_messages_status_valid')),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_messages_retry_count_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_messages_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_messages_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quoted_message_id'], ['messages.id'], name=op.f('fk_messages_quoted_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_account_status_created', 'messages', ['account_id', 'status', 'created_at'], unique=False)
    op.create_index(
        'ix_messages_conversation_created_id',
        'messages',
        ['conversation_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')],
        unique=False,
    )
    op.create_index('uq_messages_account_wa_message_id_not_null', 'messages', ['account_id', 'wa_message_id'], unique=True, sqlite_where=sa.text('wa_message_id IS NOT NULL'), postgresql_where=sa.text('wa_message_id IS NOT NULL'))
    op.create_table('outbox_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'claimed', 'completed', 'failed', 'dead')", name=op.f('ck_outbox_messages_status_valid')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_outbox_messages_attempts_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_outbox_messages_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_outbox_messages_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages')),
    sa.UniqueConstraint('idempotency_key', name='uq_outbox_messages_idempotency_key'),
    sa.UniqueConstraint('message_id', name='uq_outbox_messages_message_id')
    )
    op.create_index('ix_outbox_messages_account_status_available', 'outbox_messages', ['account_id', 'status', 'available_at'], unique=False)
    op.create_index('ix_outbox_messages_lease_expires', 'outbox_messages', ['lease_expires_at'], unique=False)
    op.create_index('ix_outbox_messages_status_available', 'outbox_messages', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_messages_status_available', table_name='outbox_messages')
    op.drop_index('ix_outbox_messages_lease_expires', table_name='outbox_messages')
    op.drop_index('ix_outbox_messages_account_status_available', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index('uq_messages_account_wa_message_id_not_null', table_name='messages', sqlite_where=sa.text('wa_message_id IS NOT NULL'), postgresql_where=sa.text('wa_message_id IS NOT NULL'))
    op.drop_index('ix_messages_conversation_created_id', table_name='messages')
    op.drop_index('ix_messages_account_status_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_account_pinned_last_message', table_name='conversations')
    op.drop_index('ix_conversations_account_archived_last_message', table_name='conversations')
    op.drop_index('ix_conversations_account_unread', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('contact_ai_overrides')
    op.drop_index('ix_whatsapp_events_account_status_occurred', table_name='whatsapp_events')
    op.drop_table('whatsapp_events')
    op.drop_index('ix_contacts_account_phone_number', table_name='contacts')
    op.drop_index('ix_contacts_account_display_name', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('uq_whatsapp_accounts_one_primary', table_name='whatsapp_accounts', sqlite_where=sa.text('is_primary = 1'), postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_table('whatsapp_accounts')
    op.drop_table('ai_runtime_settings')
    op.drop_table('ai_profiles')
    # ### end Alembic commands ###
