"""ai_relationship_intelligence

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-11 01:16:21.222916
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('contacts', sa.Column('profile_revision', sa.Integer(), nullable=False, server_default='0'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('parent_job_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_completed', sa.Integer(), nullable=False),
    sa.Column('progress_failed', sa.Integer(), nullable=False),
    sa.Column('budget_tokens', sa.BigInteger(), nullable=False),
    sa.Column('budget_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'claimed', 'running', 'retry', 'completed', 'failed', 'dead', 'cancelled')", name=op.f('ck_analysis_jobs_analysis_jobs_status_valid')),
    sa.CheckConstraint('attempts >= 0 AND max_attempts > 0 AND attempts <= max_attempts', name=op.f('ck_analysis_jobs_analysis_jobs_attempts_valid')),
    sa.CheckConstraint('budget_tokens >= 0 AND budget_cost >= 0', name=op.f('ck_analysis_jobs_analysis_jobs_budget_non_negative')),
    sa.CheckConstraint('priority >= 0', name=op.f('ck_analysis_jobs_analysis_jobs_priority_non_negative')),
    sa.CheckConstraint('progress_total >= 0 AND progress_completed >= 0 AND progress_failed >= 0', name=op.f('ck_analysis_jobs_analysis_jobs_progress_non_negative')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_analysis_jobs_analysis_jobs_version_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_analysis_jobs_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_analysis_jobs_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_analysis_jobs_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['analysis_jobs.id'], name=op.f('fk_analysis_jobs_parent_job_id_analysis_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs')),
    sa.UniqueConstraint('account_id', 'idempotency_key', name='uq_analysis_jobs_scope_idempotency')
    )
    op.create_index('ix_analysis_jobs_parent_status', 'analysis_jobs', ['parent_job_id', 'status'], unique=False)
    op.create_index('ix_analysis_jobs_status_lease_expires', 'analysis_jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_analysis_jobs_account_status_priority_available_created', 'analysis_jobs', ['account_id', 'status', sa.literal_column('priority DESC'), 'available_at', 'created_at'], unique=False)
    op.create_table('profile_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('claim_key', sa.String(length=255), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('manual_lock', sa.Boolean(), nullable=False),
    sa.Column('analyzer_version', sa.String(length=128), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sensitivity IN ('normal', 'private', 'restricted')", name=op.f('ck_profile_claims_profile_claims_sensitivity_valid')),
    sa.CheckConstraint("source_type IN ('explicit_fact', 'observed_pattern', 'model_inference', 'manual')", name=op.f('ck_profile_claims_profile_claims_source_type_valid')),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'rejected', 'superseded', 'expired')", name=op.f('ck_profile_claims_profile_claims_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_profile_claims_profile_claims_confidence_range')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_profile_claims_profile_claims_version_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_profile_claims_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_profile_claims_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_profile_claims_conversation_id_conversations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_claims')),
    sa.UniqueConstraint('account_id', 'contact_id', 'claim_key', 'version', name='uq_profile_claims_scope_key_version')
    )
    op.create_index('ix_profile_claims_account_contact_status_key_updated', 'profile_claims', ['account_id', 'contact_id', 'status', 'claim_key', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('profile_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_claim_cursor', sa.String(length=255), nullable=True),
    sa.Column('source_claim_versions', sa.JSON(), nullable=False),
    sa.Column('source_profile_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_profile_snapshots_profile_snapshots_version_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_profile_snapshots_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_profile_snapshots_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_profile_snapshots_conversation_id_conversations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_snapshots')),
    sa.UniqueConstraint('account_id', 'contact_id', 'version', name='uq_profile_snapshots_scope_version')
    )
    op.create_index('ix_profile_snapshots_account_contact_current', 'profile_snapshots', ['account_id', 'contact_id', 'is_current'], unique=False)
    op.create_index('uq_profile_snapshots_one_current', 'profile_snapshots', ['account_id', 'contact_id'], unique=True, sqlite_where=sa.text('is_current = 1'), postgresql_where=sa.text('is_current IS TRUE'))
    op.create_table('conversation_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('start_message_id', sa.String(length=36), nullable=False),
    sa.Column('end_message_id', sa.String(length=36), nullable=False),
    sa.Column('start_cursor', sa.String(length=255), nullable=True),
    sa.Column('end_cursor', sa.String(length=255), nullable=True),
    sa.Column('analyzer_version', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'stale')", name=op.f('ck_conversation_segments_conversation_segments_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_conversation_segments_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversation_segments_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_segments_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['end_message_id'], ['messages.id'], name=op.f('fk_conversation_segments_end_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_message_id'], ['messages.id'], name=op.f('fk_conversation_segments_start_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_segments')),
    sa.UniqueConstraint('account_id', 'conversation_id', 'start_message_id', 'end_message_id', 'analyzer_version', 'content_hash', name='uq_conversation_segments_scope_range_analyzer_hash')
    )
    op.create_index('ix_conversation_segments_account_conversation_end_cursor', 'conversation_segments', ['account_id', 'conversation_id', sa.literal_column('end_cursor DESC')], unique=False)
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('memory_key', sa.String(length=255), nullable=False),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_ref', sa.String(length=255), nullable=True),
    sa.Column('source_claim_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'rejected', 'expired', 'deleted')", name=op.f('ck_memory_items_memory_items_status_valid')),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name=op.f('ck_memory_items_memory_items_importance_range')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_memory_items_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_memory_items_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_memory_items_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_claim_id'], ['profile_claims.id'], name=op.f('fk_memory_items_source_claim_id_profile_claims'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_items')),
    sa.UniqueConstraint('account_id', 'contact_id', 'memory_key', name='uq_memory_items_scope_key')
    )
    op.create_index('ix_memory_items_account_contact_status_expires', 'memory_items', ['account_id', 'contact_id', 'status', 'expires_at'], unique=False)
    op.create_index('ix_memory_items_account_contact_status_updated', 'memory_items', ['account_id', 'contact_id', 'status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('profile_claim_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('excerpt_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_type IN ('message', 'summary', 'manual_note')", name=op.f('ck_profile_claim_evidence_profile_claim_evidence_type_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_profile_claim_evidence_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['profile_claims.id'], name=op.f('fk_profile_claim_evidence_claim_id_profile_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_profile_claim_evidence_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_profile_claim_evidence_conversation_id_conversations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_claim_evidence')),
    sa.UniqueConstraint('account_id', 'claim_id', 'evidence_type', 'evidence_id', name='uq_profile_claim_evidence_scope_claim_type_evidence')
    )
    op.create_index('ix_profile_claim_evidence_account_contact_claim', 'profile_claim_evidence', ['account_id', 'contact_id', 'claim_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('summary_type', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('analyzer_version', sa.String(length=128), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_summary_id', sa.String(length=36), nullable=True),
    sa.Column('source_cursor_start', sa.String(length=255), nullable=True),
    sa.Column('source_cursor_end', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'stale', 'superseded')", name=op.f('ck_conversation_summaries_conversation_summaries_status_valid')),
    sa.CheckConstraint("summary_type IN ('segment', 'daily', 'weekly', 'rolling')", name=op.f('ck_conversation_summaries_conversation_summaries_type_valid')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_conversation_summaries_conversation_summaries_version_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], name=op.f('fk_conversation_summaries_account_id_whatsapp_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversation_summaries_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_summaries_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['conversation_segments.id'], name=op.f('fk_conversation_summaries_segment_id_conversation_segments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_summary_id'], ['conversation_summaries.id'], name=op.f('fk_conversation_summaries_supersedes_summary_id_conversation_summaries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_summaries')),
    sa.UniqueConstraint('account_id', 'conversation_id', 'summary_type', 'analyzer_version', 'input_hash', name='uq_conversation_summaries_scope_type_analyzer_input')
    )
    op.create_index('ix_conversation_summaries_account_contact_status_updated', 'conversation_summaries', ['account_id', 'contact_id', 'status', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_conversation_summaries_account_contact_status_updated', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index('ix_profile_claim_evidence_account_contact_claim', table_name='profile_claim_evidence')
    op.drop_table('profile_claim_evidence')
    op.drop_index('ix_memory_items_account_contact_status_updated', table_name='memory_items')
    op.drop_index('ix_memory_items_account_contact_status_expires', table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index('ix_conversation_segments_account_conversation_end_cursor', table_name='conversation_segments')
    op.drop_table('conversation_segments')
    op.drop_index('uq_profile_snapshots_one_current', table_name='profile_snapshots', sqlite_where=sa.text('is_current = 1'), postgresql_where=sa.text('is_current IS TRUE'))
    op.drop_index('ix_profile_snapshots_account_contact_current', table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    op.drop_index('ix_profile_claims_account_contact_status_key_updated', table_name='profile_claims')
    op.drop_table('profile_claims')
    op.drop_index('ix_analysis_jobs_account_status_priority_available_created', table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_status_lease_expires', table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_parent_status', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_column('contacts', 'profile_revision')
